config/routes.rb
Photo::Application.routes.draw do
  resources :directories

  get 'admin' => "admin#index"

	controller :sessions do
		get 'login' => :new
		post 'login' => :create 
		get 'logout' => :destroy
	end
	

	resources :users
  resources :images
	
	

  get "home/index"
	
	root :to => "images#index"
	

end

app/models/directory.rb
class Directory < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :directory
	has_attached_file :picture, :styles => {:medium => "300x300>", :thumb => "100x100>" }


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :images
	validates :name, presence: true, uniqueness: true
	has_secure_password

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	#skip_before_filter :authorize
  def index
		@total_images = Image.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :getCurrentUser?
	helper_method :isLoggedIn?
  protect_from_forgery
	before_filter :authorize

	def getCurrentUser?
		user = User.find_by_id(session[:user_id])
		if user.nil?
			"Guest"
		else
			 user.name
		end
	end

	def isLoggedIn?
		if session[:user_id].nil?
			return false
		end
		return true
	end

	protected
		def authorize
			unless User.find_by_id(session[:user_id])
			redirect_to login_url, notice: "Please log in" end
		end
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directories }
    end
  end

  # GET /directories/1
  # GET /directories/1.json
  def show
    @directory = Directory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @directory }
    end
  end

  # GET /directories/new
  # GET /directories/new.json
  def new
    @directory = Directory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @directory }
    end
  end

  # GET /directories/1/edit
  def edit
    @directory = Directory.find(params[:id])
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(params[:directory])

    respond_to do |format|
      if @directory.save
        format.html { redirect_to @directory, notice: 'Directory was successfully created.' }
        format.json { render json: @directory, status: :created, location: @directory }
      else
        format.html { render action: "new" }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directories/1
  # PUT /directories/1.json
  def update
    @directory = Directory.find(params[:id])

    respond_to do |format|
      if @directory.update_attributes(params[:directory])
        format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory = Directory.find(params[:id])
    @directory.destroy

    respond_to do |format|
      format.html { redirect_to directories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
	skip_before_filter :authorize
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])
		@image.directory_id = 1
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])
    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authorize
  def new
  end

  def create
		user = User.find_by_name(params[:name])
		if user and user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to admin_url
		else
			redirect_to login_url, alert: "Invalid login"
		end
  end

  def destroy
		session[:user_id] = nil
		redirect_to login_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController	
  # GET /users
  # GET /users.json
	skip_before_filter :authorize
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User #{@user} was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User #{@user} was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

It's <%= Time.now %><br>
There are now <%= pluralize(@total_images, "image") %>

app/views/directories/_form.html.erb
<%= form_for(@directory) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

app/views/directories/index.html.erb
<% @directories.each do |directory| %>
		<%= link_to directory.name, directory %><br>
		<% directory.images.each do |image| %>
			<%= image_tag image.picture.url(:thumb), :class => "image" %> 
		<% end %>
		<% if isLoggedIn? %>
			(
  		<%= link_to 'Edit', edit_directory_path(directory) %>
  		<%= link_to 'Destroy', directory, confirm: 'Are you sure?', method: :delete %>
			)	
		<% end %>
	<br>
<% end %>

<br />
<% if isLoggedIn? %>
	<%= link_to 'New Directory', new_directory_path %>
<% end %>

app/views/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

app/views/directories/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<p>
  <b>Name:</b>
  <%= @directory.name %>
</p>
	<% @directory.images.each do |image| %>
		<%= image.title %><br>	

		<div class="show">
			<a href="<%= image.picture.url %>" title=<%= image.title %> >
				<%= image_tag image.picture.url(:medium), :class => "image" %> 
			</a>
		</div>
	<% end %>

<% unless isLoggedIn? %>
	<%= link_to 'Edit', edit_directory_path(@directory) %> |
	<%= link_to 'Back', directories_path %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Home</p>

app/views/images/_form.html.erb
<%= form_for @image, :html => { :multipart => true }  do |f| %>
	
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :photographer %><br />
    <%= f.text_field :photographer %>
  </div>
	<%= hidden_field_tag :directory_id, 1 %>
	<%= f.file_field :picture %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<table>
<tr>
<% @images.each do |image| %>
<td>
		<div class="imagebox">
			<%= link_to image_tag(image.picture.url(:medium), :class => "image"),  image %>
			<div class="imagetext">
				<%= image.title %>
				<br>
				<%= image.description %>
				<br>
				<% if isLoggedIn? %>	
					<%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %>
				<% end %>
			</div>
	</div>
</td>
<% end %>
</tr>
</table>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<div class="show">
	<a href="<%= @image.picture.url %>" title=<%= @image.title %> >
		<%= image_tag @image.picture.url(:medium), :class => "image" %> 
	</a>
</div>
<div class="imagebox_show">
<p>
  <b>Title:</b>
  <%= @image.title %>
</p>

<p>
  <b>Title:</b>
  <%= @image.picture_file_name %>
</p>

<p>
  <b>Description:</b>
  <%= @image.description %>
</p>

<p>
	<b>Photographer</b>
	<%= @image.photographer %>
</p>
	
<div class="exif" id="exif_<%=@image.id%>" >Exif
	<div class="exifdata ">
		Cameramodel:
		<%= EXIFR::JPEG.new(@image.picture.path).model %>
		<br>
		Date:
		<%= EXIFR::JPEG.new(@image.picture.path).date_time  %>
		<br>
		Exposure:
		<%= EXIFR::JPEG.new(@image.picture.path).exposure_time.to_s  %>
		<br>
		Width:
		<%= EXIFR::JPEG.new(@image.picture.path).width %>
		<br>
		Height:
		<%= EXIFR::JPEG.new(@image.picture.path).height  %>
		<br>					
		Shutter:
		<%= EXIFR::JPEG.new(@image.picture.path).shutter_speed_value.to_s%>
		<br>					
		Aperture:
		<%= EXIFR::JPEG.new(@image.picture.path).aperture_value.to_s%>
	</div>
</div>
<% if isLoggedIn? %>
	<%= link_to 'Edit', edit_image_path(@image) %> |
	<%= link_to 'Back', images_path %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</script>
</head>
<body class="<%= controller.controller_name %>">
<div id="banner">
	<%= image_tag("logo.png") %>
	<%= @page_title || "Photo" %>
	<br>

</div>
<div id="columns">
	<div id="side"> 
		<ul>
			<li><%= link_to "Hem", root_path %></li>
			<% if session[:user_id] %>
				<li><%= link_to 'New Image', new_image_path %></li>
			<% end %> 
			<li><a href="http://www..../news">News</a></li>
		 	<li><a href="http://www..../contact">Contact</a></li>			
		</ul> 
		Logged in as <%= getCurrentUser? %>
		<div id="login_logout">
			<% if isLoggedIn? %>
				<%= link_to "Log out", login_path, method: :get %>
			<% else %>
				<%= link_to "Log in", logout_path, method: :delete %>
			<% end %>
		</div
	</div>
</div>
	<div id="main">
		<%= yield %>
	</div>


</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
	<legend>
	<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br />
    <%= f.password_field :password,size: 40 %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'Confirm Password' %><br />
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>